### PR TITLE
Allow written resolutions by majority (articles by two thirds majority)

### PR DESCRIPTION
**Pull request by nomis**
Version 4:
```
commit 534bc4848531fc605b43d80bde5ec11d6cf5e8cb
gpg: Signature made Sun 29 May 2022 12:36:36 BST
gpg:                using RSA key 307FBC1717B532F90D221897DF001BFD83E75990
Date:   Sun May 29 12:16:14 2022 +0100

    Allow written resolutions by majority (articles by two thirds majority)
```

### CODE REVIEW

**Comment by nomis** [comment]
Version 1:
```
commit 5f4f509e1ff1601df1a0537c14594ef6cfd17ae3
gpg: Signature made Sun 29 May 2022 12:25:11 BST
gpg:                using RSA key 307FBC1717B532F90D221897DF001BFD83E75990
Date:   Sun May 29 12:16:14 2022 +0100

    Allow written resolutions to change the articles by two thirds majority
```

**Comment by nomis** [comment]
> I might add something like, "To distinguish a written resolution from proposals that are not intended as resolutions, a written resolution must be clearly identified as such using the words `written resolution'"

- [ ] Written resolutions to be clearly identified

**Comment by dylan-thinnes** [comment]
Voted on in combination with PR 14. There were no votes for 12 (this PR), one vote for 14, 2 against all, and 25 abstentions. Thus, this did not pass.

**Comment by nomis** [comment]
Anyone trying to resurrect this should take into consideration that it is near impossible to get two thirds of the membership to participate in something by email, and it may not be possible to accumulate approval from two thirds of the membership in person either.

We should call an EGM if we want to amend the articles outside an AGM.

**Pull request closed without merging**
